### ISSUE TITLE
consumer async libraries and too many choices

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/wg-async-foundations#112]
### Basic summary

@nikomatsakis I'm not too sure if that story gathers my experience with Rust. I've not published a library yet, but I have consumed all the most popular ones. It seems that Alan and Barbara are "producers" (sorry, probably not a good word to describe people) of libraries.

My urge to write in this thread comes from the point of view of the "consumer". It's very likely that the library Alan and Barbara are writing has a limited scope. That in itself is a luxury, especially if they aim for one thing and one thing only. "Consumers" of libraries, on the other hand, will have a very long list of dependencies to work with: http client, http server, pub/sub routines, websockets, ORMs and database connections, caching in remote stores, etc.

In that regards, it surprised me the conversation about whether to use async or not. In the story I have in mind it's an absolute given. No one in their right mind would write a synchronous web server like it's the nineties

@eminence I'd be more than happy to write a sub-story. Maybe sub-stories could be linked to more than one (trust and http client)?. I think my story would begin with something like:

1. Someone visits https://www.arewewebyet.org/
2. As a result, s/he thinks Rust is great to write a REST API because async support seems to be ready in all those libraries
3. And then similarity with story x
4. But also something different

_Originally posted by @cortopy in https://github.com/rust-lang/wg-async-foundations/issues/95#issuecomment-811394855_

**Comment by nikomatsakis** [comment]
cc @eminence

**Comment by nikomatsakis** [comment]
I think @cortopy that I wouldn't necessarily write a *substory* -- if you want to continue a story, just reference the other story with a link in the beginning. "After Alan did foo, he ...".

**Comment by nikomatsakis** [comment]
You can still add a FAQ about one story being followed by another.

**Comment by eminence** [comment]
Yeah.  I'd say we should start by just writing the story to see how it reads.  And then later we can decide where exactly to put it (leave it as its own story, fold it into another story, add a sub-story, etc).

**Comment by nikomatsakis** [comment]
Closing since we landed https://rust-lang.github.io/wg-async-foundations/vision/status_quo/alan_picks_web_server.html
