### ISSUE TITLE
create a vision doc thanks page

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/wg-async-foundations#117]
I want to include (a) all people who commented on issues, (b) all people who opened PRs, and (c) all people who joined an AVD writing session!

**Comment by Stupremee** [comment]
Do you want to keep track of all the contributors manually or should there be some CI setup or similar that adds all people who opened a PR automatically? I guess manually tracking the contributors is much easier.

I think an additional chapter "6. Contributors" or "6. Acknowledgements" would be a really nice way to show a list of people that helped.

**Comment by nikomatsakis** [comment]
I would probably do it manually, @Stupremee -- but I was hoping to have some kind of script for scraping the folks who participated on the repo so that we can re-run it towards the end to make sure we've gotten everyone.

**Comment by nikomatsakis** [comment]
@emmanuelantony2000 [wrote a script](https://gist.github.com/emmanuelantony2000/e97a1193fe6acd3b0a9e181b672b6ca3) for gathering up the names of folks who participated in issues.

**Comment by Stupremee** [comment]
That's good. I would like to work on this. I will expand the script to also include code contributors.

**Comment by nikomatsakis** [comment]
@Stupremee yes, thanks!
