### ISSUE TITLE
convert FAQ entries from bulleted lists to sections

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/wg-async-foundations#118]
The FAQ entries today use nested lists, but those are annoying when you want to embed code blocks. A better choice would be use `###` sub-headings (or `####`, as the case may be). These would also be linkable. 

To make this happen you would need to basically riprep through the repo to convert the existing "Frequently Asked Questions" lists.

**Comment by Stupremee** [comment]
I would like to work on this 👍
