### ISSUE TITLE
Implicit connection or not ready

### ISSUE THREAD

**Issue by pickfire** [rust-lang/wg-async-foundations#190]
### Brief summary

Recently I worked on low-level rust async libraries, I wanted to do a simple unix stream client but after tried it out first hand as I don't usually do low-level networking in rust, I faced something which is not expected, mainly around extra connection struct and missing `poll_fn` functions.

Since I just faced this just now, I will be writing a draft on this at least it is still fresh in my mind.

### Optional details

* (Optional) Which [character(s)] would be the best fit and why?
    * [ ] [Alan]: the experienced "GC'd language" developer, new to Rust
    * [ ] [Grace]: the systems programming expert, new to Rust
    * [ ] [Niklaus]: new programmer from an unconventional background
    * [x] [Barbara]: the experienced Rust developer
* (Optional) Which [project(s)] would be the best fit and why?
    * Sending a/multiple HTTP request using unix stream.
* (Optional) What are the key points or morals to emphasize?
    * The types in low-level rust networking (talking about hyper but could happen to others) are quite implicit, the users have to carefully check whether polling manually is required and check each output type one by one to make sure it will work.

[character(s)]: https://rust-lang.github.io/wg-async-foundations/vision/characters.html
[project(s)]: https://rust-lang.github.io/wg-async-foundations/vision/projects.html
[Alan]: https://rust-lang.github.io/wg-async-foundations/vision/characters/alan.html
[Grace]: https://rust-lang.github.io/wg-async-foundations/vision/characters/grace.html
[Niklaus]: https://rust-lang.github.io/wg-async-foundations/vision/characters/niklaus.html
[Barbara]: https://rust-lang.github.io/wg-async-foundations/vision/characters/barbara.html

**Comment by pickfire** [comment]
https://hackmd.io/@G8ZK5BSuQPOxvEQWVZSxng/BJs4pk1_O/edit

**Comment by Stupremee** [comment]
The HackMD is private :(

**Comment by nikomatsakis** [comment]
@pickfire the status quo is not late! We are still eagerly accepting status quo stories :)

**Comment by nikomatsakis** [comment]
but yes, i can't read it. I say just open a PR
