### ISSUE TITLE
Libraries trend towards thread-safety, even if users don't

### ISSUE THREAD

**Issue by anp** [rust-lang/wg-async-foundations#212]
(Note: I'm not quite sure how to express this as a story without context like "you might want a singlethreaded executor" that doesn't seem super common in the other stories. Advice on framing appreciated!)

### Brief summary

TLDR, if implementing shared library code which of these two should you pick?

```rust
struct Foo {
    cached_subfoos: Arc<Mutex<FooStore>>,
}

// ... or ...

struct Foo {
    cached_subfoos: Rc<RefCell<FooStore>>,
}
```

* implementing library with shared state and/or interior mutability
* need to choose between Rc/Arc and RefCell/Mutex for sharing & mutability and spawning local or Send tasks for async work
* this choice affects the `Send`ness of futures working with the library types
* choosing Rc/RefCell means the library cannot be used in some contexts
* choosing Arc/Mutex is extra overhead in singlethreaded contexts
* offering both "local" and "send" variants of library types is a lot of work if it is feasible at all
* if you only implement one, it's hard to get away with the Rc/RefCell version because it won't work at all in a lot of contexts
* if you implement the Arc/Mutex version and use it in a single-threaded-only context you pay an unnecessary performance overhead
* this problem is amplified if the library accepts Futures in its APIs, as it will likely need to bound those `Future + Send`, forcing single-threaded callers to use Arc etc.

### Optional details

* (Optional) Which [character(s)] would be the best fit and why?
    * [ ] [Alan]: the experienced "GC'd language" developer, new to Rust
    * [ ] [Grace]: the systems programming expert, new to Rust
    * [ ] [Niklaus]: new programmer from an unconventional background
    * [x] [Barbara]: the experienced Rust developer
      * an experienced rustacean is more likely to be implementing libraries for others' consumption where performance tradeoffs matter
      * it's reasonable for a less experienced rust developer to default to Send types everywhere
      * other developers would still likely encounter this as a confusing decision point rather than a frustrating boundary on what they can achieve
* (Optional) What are the key points or morals to emphasize?
  * in synchronous Rust this design choice boils down to "can this library be used with concurrency" but async introduces single-threaded concurrency and more nuance to design tradeoffs

### References

Not sure how to capture this but on Fuchsia, something like 99% of Rust code runs in singlethreaded async contexts that could benefit from `!Send` optimization, but the remaining 1% effectively forces our most common shared libraries to be all-`Send`. I can produce a more formal analysis if that would be helpful.

[character(s)]: https://rust-lang.github.io/wg-async-foundations/vision/characters.html
[project(s)]: https://rust-lang.github.io/wg-async-foundations/vision/projects.html
[Alan]: https://rust-lang.github.io/wg-async-foundations/vision/characters/alan.html
[Grace]: https://rust-lang.github.io/wg-async-foundations/vision/characters/grace.html
[Niklaus]: https://rust-lang.github.io/wg-async-foundations/vision/characters/niklaus.html
[Barbara]: https://rust-lang.github.io/wg-async-foundations/vision/characters/barbara.html

**Comment by tmandry** [comment]
> (Note: I'm not quite sure how to express this as a story without context like "you might want a singlethreaded executor" that doesn't seem super common in the other stories. Advice on framing appreciated!)

You could say Barbara is working on a system service that needs concurrency but not parallelism and wants to conserve resources, or something.

**Comment by pickfire** [comment]
Yup, this happened to actix-web. They don't require `Sync` but most other libraries have `Sync` which is not necessary. So if you use actix-web and use other async libraries, it may require `Sync` but actually it does not. They don't let you have the choice of `Rc` and `Arc` like standard library does.

**Comment by betamos** [comment]
Great summary of the issue. Some related thoughts:

- This issues arise specifically with reference counted mutual exclusion (the famous `Arc<Mutex<T>>`), which is very common but can often be substituted for plain mutable objects and message passing between tasks. First class support and docs for message passing as an alternative can mitigate some of the impact of these issues.
- Even if we can't abstract over send-ness in all cases today due to various reasons, we could provide API compatible (modulo sendness) types – either in the standard library or a third-party library (think a `std::sync_singlethreaded::Mutex` that uses the Mutex API as opposed to the RefCell API). This would reduce cognitive load and make refactors trivial search-and-replace (but again, doesn't solve the generic library use-case).

**Comment by pickfire** [comment]
> This issues arise specifically with reference counted mutual exclusion (the famous Arc<Mutex<T>>), which is very common but can often be substituted for plain mutable objects and message passing between tasks. First class support and docs for message passing as an alternative can mitigate some of the impact of these issues.

An example of what library author will say. https://github.com/diesel-rs/diesel/issues/399#issuecomment-850826567

Usually they would prefer having one API that can cover everyone use cases, unlike rust which provides one that cover a specific use case and one that cover another use case, for zero cost. Maintaining a faster implementation does not always justify the cost when the range that required to be changed is huge.

Sounds like specialization but over types to me.

**Comment by anp** [comment]
Thank you all for the feedback! I've opened https://github.com/rust-lang/wg-async-foundations/pull/216.
