### ISSUE TITLE
Alan becomes a better C# programmer

### ISSUE THREAD

**Issue by MidasLamb** [rust-lang/wg-async-foundations#84]
First of all, I'm not quite sure if these kinds of stories are relevant, but most of the status quo stories highlight the issues of the current state, while there are also good things that came forth from it, which might be important to highlight in order not to lose them.
If these kinds of stories are also useful, I can myself try to write it out, but I first wanted to see if it is useful.

### Brief summary

Alan(/Niklaus?) has been writing asynchronous C# code for a while now. Plop down an `await` here, change the return type to `Task`, and so on. His code works and seems to perform fine.

On his journey through async Rust, he learned about some of the internals about Futures/Executors/... and gained a deeper level of understanding about what asynchronous code really is.

Now when writing async C#, he reasons more about what is really happening, and has become the "goto async C# expert" of his team, not necessarily because he learned more about async C#, but because he learned about async Rust.

### Optional details

* What are the key points or morals to emphasize?
    * Rust is known for its steep learning curve, but (I think) many people can agree that once you get past that initial curve, you grow as a developer. The same might hold true for async Rust. Just as the borrow checker is something you just need to learn about if you want to write decent Rust code, there might just be an "async borrow checker" (I.e. something you just need to learn in order to effectively utilize it, I do not mean a separate borrow checker for asynchronous Rust code)

**Comment by nikomatsakis** [comment]
I've been pondering this -- the question of negatives vs positives. I think writing a story like this could be really great!

**Comment by nikomatsakis** [comment]
That said, @MidasLamb -- maybe just add this to your existing PR?

**Comment by rylev** [comment]
I think this would be good to add to the existing PR. I imagine the shiny future, we'll ultimately end up with isn't one where those writing async Rust can rely on being completely abstracted away from the details, but hopefully getting into async won't require learning _everything_ all at once as it can often seem like it does today. 

Becoming an effective Rust programmer usually involves the user grappling with concepts that many programmers don't need to care about as much like stack vs heap, memory layout, etc., but these concepts aren't *required* knowledge for writing basic Rust code. So should things like `Pin` and executors not be required for writing basic async Rust.

**Comment by MidasLamb** [comment]
> That said, @MidasLamb -- maybe just add this to your existing PR?

@nikomatsakis , I'll add it to #85 , I wasn't sure if it this could be incorporated there or if this was more of a stand-alone story.

> ...but these concepts aren't required knowledge for writing basic Rust code. ...

@rylev, I agree, that was what I was alluding to with the "async borrow checker". You can get a lot of programs to compile by just appending `.clone()` everywhere and avoiding references, but that's not efficient/good Rust code, effectively ignoring the borrow checker. To write efficient/good Rust code, you'll learn about why the borrow checker allows/disallows certain things. A "parallel" might exist in async Rust.

**Comment by MidasLamb** [comment]
Has been added to #70
